In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv('Social_Network_Ads.csv')

In [4]:
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
x = data.drop('Purchased',axis = 1)
y = data['Purchased']

In [6]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.3 , random_state = 42)

In [7]:
X_train.shape,X_test.shape

((280, 4), (120, 4))

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [20]:
ohe = OneHotEncoder(drop = 'first')
scaler = StandardScaler()

In [21]:
data['User ID'].duplicated().sum()

np.int64(0)

In [22]:
X_train

      User ID  Gender  Age  EstimatedSalary
157  15602373    Male   29            75000
109  15697997  Female   38            80000
17   15617482    Male   45            26000
347  15768151  Female   54           108000
24   15705113    Male   46            23000
..        ...     ...  ...              ...
71   15726358  Female   24            27000
106  15706185  Female   26            35000
270  15680752  Female   43           133000
348  15579212    Male   39            77000
102  15584545  Female   32            86000

[280 rows x 4 columns]

In [23]:
from sklearn import set_config
set_config(display='text')

In [24]:
preprocessor = ColumnTransformer(
transformers = [
    ('OHE',ohe,[1]),
    ('STANDARD.',scaler,[2,3])
],
remainder = 'passthrough'
)

In [25]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('OHE', OneHotEncoder(drop='first'), [1]),
                                ('STANDARD.', StandardScaler(), [2, 3])])

# Code	               Meaning
# fit()	               Learn preprocessing rules
# transform()     	   Apply learned rules
# fit_transform()	   Learn + apply together

In [26]:
X_train_dummy = preprocessor.fit_transform(X_train)
X_test_dummy = preprocessor.transform(X_test)

In [27]:
X_train_dummy

array([[ 1.00000000e+00, -8.42521543e-01,  1.30156299e-01,
         1.56023730e+07],
       [ 0.00000000e+00,  4.17576275e-02,  2.77701902e-01,
         1.56979970e+07],
       [ 1.00000000e+00,  7.29530315e-01, -1.31579061e+00,
         1.56174820e+07],
       ...,
       [ 0.00000000e+00,  5.33023833e-01,  1.84168529e+00,
         1.56807520e+07],
       [ 1.00000000e+00,  1.40010869e-01,  1.89174540e-01,
         1.55792120e+07],
       [ 0.00000000e+00, -5.47761819e-01,  4.54756625e-01,
         1.55845450e+07]], shape=(280, 4))

In [29]:
preprocessor.get_feature_names_out()

array(['OHE__Gender_Male', 'STANDARD.__Age', 'STANDARD.__EstimatedSalary',
       'remainder__User ID'], dtype=object)